server:
  port: 8086
spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
#    url: jdbc:h2:tcp://localhost/~/test
#    driver-class-name: org.h2.Driver
#    username: sa
      url: jdbc:mysql://192.168.0.50/matrix_hhw?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      driver-class-name: com.mysql.jdbc.Driver
      username: matrix_hhw
      password: matrix_hhw
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

security:
  oauth2:
#    client:
#      client-id: testClientId
#      client-secret: testSecret
#    resource:
#      token-info-uri: http://localhost:8084/oauth/check_token
    jwt:
      signkey: 123@#$